-- MySQL Script generated by MySQL Workbench
-- Tue Mar 31 12:28:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USERS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `pwd` CHAR(64) NOT NULL,
  `admin` TINYINT NULL,
  `score` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORY` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DRAWING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DRAWING` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `USERS_id` INT NOT NULL,
  `CATEGORY_id` INT NOT NULL,
  `location` VARCHAR(200) NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'U',
  `score` INT NULL,
  `time` INT NOT NULL,
  PRIMARY KEY (`id`, `USERS_id`, `CATEGORY_id`),
  INDEX `fk_DRAWING_USERS_idx` (`USERS_id` ASC) VISIBLE,
  INDEX `fk_DRAWING_CATEGORY1_idx` (`CATEGORY_id` ASC) VISIBLE,
  CONSTRAINT `fk_DRAWING_USERS`
    FOREIGN KEY (`USERS_id`)
    REFERENCES `mydb`.`USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DRAWING_CATEGORY1`
    FOREIGN KEY (`CATEGORY_id`)
    REFERENCES `mydb`.`CATEGORY` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NOTATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NOTATION` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `score` VARCHAR(200) NOT NULL,
  `USERS_id` INT NOT NULL,
  `DRAWING_id` INT NOT NULL,
  `DRAWING_USERS_id` INT NOT NULL,
  `DRAWING_CATEGORY_id` INT NOT NULL,
  PRIMARY KEY (`id`, `USERS_id`, `DRAWING_id`, `DRAWING_USERS_id`, `DRAWING_CATEGORY_id`),
  INDEX `fk_NOTATION_USERS1_idx` (`USERS_id` ASC) VISIBLE,
  INDEX `fk_NOTATION_DRAWING1_idx` (`DRAWING_id` ASC, `DRAWING_USERS_id` ASC, `DRAWING_CATEGORY_id` ASC) VISIBLE,
  CONSTRAINT `fk_NOTATION_USERS1`
    FOREIGN KEY (`USERS_id`)
    REFERENCES `mydb`.`USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTATION_DRAWING1`
    FOREIGN KEY (`DRAWING_id` , `DRAWING_USERS_id` , `DRAWING_CATEGORY_id`)
    REFERENCES `mydb`.`DRAWING` (`id` , `USERS_id` , `CATEGORY_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MODELS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MODELS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `epochs` INT NOT NULL,
  `accuracy` DOUBLE NOT NULL,
  `loss` DOUBLE NOT NULL,
  `val_accuracy` DOUBLE NOT NULL,
  `val_loss` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RULES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RULES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_param` VARCHAR(200) NULL,
  `second_param` VARCHAR(200) NULL,
  `MODELS_id` INT NOT NULL,
  PRIMARY KEY (`id`, `MODELS_id`),
  INDEX `fk_RULES_MODELS1_idx` (`MODELS_id` ASC) VISIBLE,
  CONSTRAINT `fk_RULES_MODELS1`
    FOREIGN KEY (`MODELS_id`)
    REFERENCES `mydb`.`MODELS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
